# Generated by Django 4.2.1 on 2024-06-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdmin', '0002_alter_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='type',
            field=models.CharField(choices=[('SU', 'superuser'), ('CS', 'customer support'), ('CU', 'customer user'), ('QA', 'quality assurance')], default='CU', max_length=2),
        ),
    ]
